name: Build and Release Docker Image

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v' (e.g., v1.0.0)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # Or specify a subdirectory if needed
          file: ./Dockerfile # Path to your Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPOSITORY }}:${{ github.ref_name }}

      - name: Logout of Docker Hub
        uses: docker/logout-action@v2

  create-release:
    needs: build-and-push # Run after the build job
    runs-on: ubuntu-latest
    permissions:
      releases: write # Required to create releases

    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.event.repository.name }} # Upload the downloaded artifact
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Automated release for tag ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
