apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ilpostapi
build:
  artifacts:
    - image: ilpostapi
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - 'src/database/__init__.py'
          - 'src/**/*.py'
          - 'src/**/*.html'
          - 'src/**/*.css'
          - 'src/**/*.js'
          - 'src/**/*.json'
          - 'src/**/*.txt'
          - 'src/**/*.yaml'
          - 'src/**/*.yml'

portForward:
- resourceType: deployment
  resourceName: ilpostapi
  port: 5000
  address: 0.0.0.0
  localPort: 5000

manifests:
  helm:
    releases:
      - name: ilpostapi
        remoteChart: bjw-s/app-template
        valuesFiles:
          - deploy/helm/values.yaml
        setValueTemplates:
          controllers.main.containers.main.image.repository: "{{.IMAGE_REPO_ilpostapi}}"
          controllers.main.containers.main.image.tag: "{{.IMAGE_TAG_ilpostapi}}"
        createNamespace: true
deploy:
  helm:
    hooks:
      before:
        - host:
            command: ["sh", "deploy/hooks/check-secret.sh"]
