apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ilpostapi
build:
  artifacts:
    - image: ilpostapi
      sync:
        infer:
          - src/*
  local:
    useBuildkit: true
manifests:
  kustomize:
    paths:
    - "deploy/k8s"
portForward:
  - resourceType: deployment
    resourceName: ilpostapi
    port: 5000
    address: 0.0.0.0
deploy:
  kubectl: {}